### ISSUE TITLE
Схема базы данных

### ISSUE THREAD

**Issue by Sywooch** [ShNURoK42/linuxforum#2]
Здравствуйте!
Не собираетесь добавить в миграции схему базы данных или sql файл со схемой,
а так же примеры console-local.php, main-local.php?
Как я понимаю, за основу был взят Yii-QA?

**Comment by ShNURoK42** [comment]
Здравствуйте!
Планы конечно есть, но пока не хвататет времени, если вы заинтересованы в скрипте, могу сделать, тоже касается и локальных настроек.
Что касается базы, то за основу был взят [punbb](https://github.com/punbb/punbb), так как форум переводил с этого скрипта, никакие системы написанные на yii1/2 не использовались.
Так как сейчас идет активная разработка и постоянно вносятся изменения, то поэтому я и не делал миграций.
Дело в том, что на данный момент функционал отсутствует, есть только регистрация, логин, создание тем, сообщений и редактирование сообщений. Больше ничего нет, админ панели тоже нет.

**Comment by Sywooch** [comment]
Сасибо за ответ!
Я конечно заинтерисован в скрипте и с любопытством наблюдаю за ним некоторое время.
Уж было надумал схему базы по моделям рисовать ))

**Comment by ShNURoK42** [comment]
Давайте я на днях сделаю миграции, загадывать не буду, но думаю это много времени не займет.

**Comment by Sywooch** [comment]
Спасибо большое!

**Comment by ShNURoK42** [comment]
@Sywooch добавил миграции и скелет локальньного конфига.
Прошу прощения, что так долго.

**Comment by Sywooch** [comment]
Спасибо большое!
