### ISSUE TITLE
XSS protection

### ISSUE THREAD

**Issue by JiLiZART** [ShNURoK42/linuxforum#4]
http://www.yiiframework.com/doc-2.0/guide-security-best-practices.html
http://linuxforum.ru/topic/38173

**Comment by ShNURoK42** [comment]
Спасибо большое.
Адрес вашей электронной почты я убрал из заголовка.

**Comment by JiLiZART** [comment]
Тема не моя )

**Comment by ShNURoK42** [comment]
Тогда остается надеется, что автор сюда напишет, так как темы я удалил.
