### ISSUE TITLE
update /search/active_topics, /search/unanswered_topics

### ISSUE THREAD

**Issue by tecnologiaterabyte** [ShNURoK42/linuxforum#5]
Excellent forum for yii2, it would be nice If you could update the repo,  I think update to install on yii2-advanced-app,

Thks,

Wilmer.

**Comment by ShNURoK42** [comment]
Hi,
sorry, I don't understand, can you tell me, what do you mean?

**Comment by tecnologiaterabyte** [comment]
Hi @ShNURoK42 views:

    'topic/search/view-active-topics'
    'topic/search/view-unanswered-topics'
    'topic/search/view-ownpost-topics'

Not exist in the repo, you could update it,

Thks,

Wilmer.

**Comment by ShNURoK42** [comment]
@tecnologiaterabyte this files don't use now. Can you say where you have errors with it?
Now for render this pages use only one view /modules/topic/views/search/topic_list.php

**Comment by tecnologiaterabyte** [comment]
On no problem, Could you tell me what the new routes for the buttons in the menu

            <div class="btn-group">
                <?php if (!Yii::$app->getUser()->getIsGuest()):?>
                <a class="btn btn-sm btn-outline" title="Темы в которых вы отвечали." href="/search/ownpost_topics">Ваши темы</a>
                <?php endif; ?>
                <a class="btn btn-sm btn-outline" title="Темы с сортировкой по активности." href="/search/active_topics">Активные темы</a>
                <a class="btn btn-sm btn-outline" title="Темы без ответов." href="/search/unanswered_topics">Темы без ответов</a>
            </div>

Thks,

Wilmer.

**Comment by ShNURoK42** [comment]
Thanks, I understand. Fix it.

**Comment by tecnologiaterabyte** [comment]
No problem, I will contribute with the same,

Thks,

Wilmer.
